AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyFunction:
    Properties:
      CodeUri: s3://unicorn-artifacts/bdca869ab5f4e023cf39de21cce73bde
      Handler: app.anonamize
      Runtime: nodejs6.10
      Timeout: 300
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
