AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  MyFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.anonamize
      Runtime: nodejs6.10
      CodeUri: './src'
  MyAPI:
    Type: 'AWS::Serverless::Api'
    Properties:
      DefinitionBody: anonna-serverless-v1_1-swagger.yaml
      Stage: v1.2
